import {
  faCalendarCheck,
  faChartLine,
  faExclamation,
  faHandHoldingDollar,
  faHandshake,
  faHeadset,
  faMagnifyingGlass,
  faPeopleGroup,
  faScrewdriverWrench,
  faToolbox,
  faUserSecret,
  faUserTie,
} from "@fortawesome/free-solid-svg-icons";
import {
  AttendancePage,
  ChargesPage,
  CustomersPage,
  DirectionPage,
  EquipmentPage,
  HomePage,
  LoginPage,
  PendenciesPage,
  SalesPage,
  SchedulesPage,
  SettingsPage,
  SinistersPage,
  SupervisionPage,
} from "../pages";



export const ROUTES_PATHS = [

  {
    path: '/Atendimento',
    element: AttendancePage,
    title: 'Atendimento',
    label: 'Atendimento',
    isPrivate: true,
    Permissions: [],
    icon: faHeadset,
  },
  {
    path: '/Sinistros',
    element: SinistersPage,
    title: 'Sinistros',
    label: 'Sinistros',
    isPrivate: true,
    Permissions: [],
    icon: faUserSecret,
  },
  {
    path: '/Equipamentos',
    element: EquipmentPage,
    title: 'Equipamentos',
    label: 'Equipamentos',
    isPrivate: true,
    Permissions: [],
    icon: faToolbox,
  },

  {
    path: '/Supervisao',
    element: SupervisionPage,
    title: 'Supervisao',
    label: 'Supervisão',
    isPrivate: true,
    Permissions: [],
    icon: faMagnifyingGlass,
  },

  {
    path: '/Vendas',
    element: SalesPage,
    title: 'Vendas',
    label: 'Vendas',
    isPrivate: true,
    Permissions: [],
    icon: faHandshake,
  },
  {
    path: '/Clientes',
    element: CustomersPage,
    title: 'Clientes',
    label: 'Clientes',
    isPrivate: true,
    Permissions: [],
    icon: faPeopleGroup,
  },
  {
    path: '/Cobrancas',
    element: ChargesPage,
    title: 'Cobrancas',
    label: 'Cobranças',
    isPrivate: true,
    Permissions: [],
    icon: faHandHoldingDollar,
  },

  {
    path: '/Diretoria',
    element: DirectionPage,
    title: 'Diretoria',
    label: 'Diretoria',
    isPrivate: true,
    icon: faUserTie,

    Permissions: [],
  },
  {
    path: '/Pendencias',
    element: PendenciesPage,
    title: 'Pendencias',
    label: 'Pendências',
    isPrivate: true,
    Permissions: [],
    icon: faExclamation,
  },
  {
    path: '/Agenda',
    element: SchedulesPage,
    title: 'Agenda',
    label: 'Agenda',
    isPrivate: true,
    Permissions: [],
    icon: faCalendarCheck,
  },

  {
    path: '/Sumario',
    element: HomePage,
    title: 'Sumario',
    label: 'Sumário',
    isPrivate: true,
    Permissions: [],
    icon: faChartLine,
  },
  {
    path: '/Configuracoes',
    element: SettingsPage,
    title: 'Configuracoes',
    label: 'Configurações',
    isPrivate: true,
    Permissions: [],
    icon: faScrewdriverWrench,
  },
  {
    path: "/",
    element: LoginPage,
    title: "Login",
    isPrivate: false,
  },
];
