import {
  AttendancePage,
  ChargesPage,
  CustomersPage,
  DirectionPage,
  EquipmentPage,
  HomePage,
  LoginPage,
  PendenciesPage,
  SchedulesPage,
  SettingsPage,
  SinistersPage,
  SupervisionPage,
  TestesPage,
} from "../pages";

export const ROUTES_PATHS = [
  {
    path: "/home",
    element: HomePage,
    title: "Sumario",
    isPrivate: true,
    permissions: [],
  },
  {
    path: "/Atendimento",
    element: AttendancePage,
    title: "Atendimento",
    isPrivate: true,
    Permissions: [],
  },
  {
    path: "/Vendas",
    element: ChargesPage,
    title: "Vendas",
    isPrivate: true,
    Permissions: [],
  },
  {
    path: "/Pendencias",
    element: PendenciesPage,
    title: "Pendencias",
    isPrivate: true,
    Permissions: [],
  },
  {
    path: "/Sinistros",
    element: SinistersPage,
    title: "Sinistros",
    isPrivate: true,
    Permissions: [],
  },
  {
    path: "/Cobrancas",
    element: ChargesPage,
    title: "Cobrancas",
    isPrivate: true,
    Permissions: [],
  },
  {
    path: "/Clientes",
    element: CustomersPage,
    title: "Clientes",
    isPrivate: true,
    Permissions: [],
  },
  {
    path: "/Agenda",
    element: SchedulesPage,
    title: "Agenda",
    isPrivate: true,
    Permissions: [],
  },
  {
    path: "/Equipamentos",
    element: EquipmentPage,
    title: "Equipamentos",
    isPrivate: true,
    Permissions: [],
  },
  {
    path: "/Supervisao",
    element: SupervisionPage,
    title: "Supervisao",
    isPrivate: true,
    Permissions: [],
  },
  {
    path: "/Diretoria",
    element: DirectionPage,
    title: "Diretoria",
    isPrivate: true,

    Permissions: [],
  },
  {
    path: "/Settings",
    element: SettingsPage,
    title: "Configuracoes",
    isPrivate: true,
    Permissions: [],
  },
  {
    path: "/aqui",
    element: TestesPage,
    title: "aqui",
    isPrivate: true,
    Permissions: [],
  },
  {
    path: "/",
    element: LoginPage,
    title: "Login",
    isPrivate: false,
  },
];
