import {
  faCalendarCheck,
  faChartLine,
  faExclamation,
  faHandHoldingDollar,
  faHandshake,
  faHeadset,
  faMagnifyingGlass,
  faPeopleGroup,
  faScrewdriverWrench,
  faToolbox,
  faUserSecret,
  faUserTie,
} from "@fortawesome/free-solid-svg-icons";
import {
  AttendancePage,
  ChargesPage,
  CustomersPage,
  DirectionPage,
  EquipmentPage,
  HomePage,
  LoginPage,
  PendenciesPage,
  SalesPage,
  SchedulesPage,
  SettingsPage,
  SinistersPage,
  SupervisionPage,
} from "../pages";

export const ROUTES_PATHS = [
  {
    path: "/Sumario",
    element: HomePage,
    title: "Sumario",
    isPrivate: true,
    permissions: [],
    icon: faChartLine,
  },
  {
    path: "/Atendimento",
    element: AttendancePage,
    title: "Atendimento",
    isPrivate: true,
    Permissions: [],
    icon: faHeadset,
  },
  {
    path: "/Vendas",
    element: SalesPage,
    title: "Vendas",
    isPrivate: true,
    Permissions: [],
    icon: faHandshake,
  },
  {
    path: "/Pendencias",
    element: PendenciesPage,
    title: "Pendencias",
    isPrivate: true,
    Permissions: [],
    icon: faExclamation,
  },
  {
    path: "/Sinistros",
    element: SinistersPage,
    title: "Sinistros",
    isPrivate: true,
    Permissions: [],
    icon: faUserSecret,
  },
  {
    path: "/Cobrancas",
    element: ChargesPage,
    title: "Cobrancas",
    isPrivate: true,
    Permissions: [],
    icon: faHandHoldingDollar,
  },
  {
    path: "/Clientes",
    element: CustomersPage,
    title: "Clientes",
    isPrivate: true,
    Permissions: [],
    icon: faPeopleGroup,
  },
  {
    path: "/Agenda",
    element: SchedulesPage,
    title: "Agenda",
    isPrivate: true,
    Permissions: [],
    icon: faCalendarCheck,
  },
  {
    path: "/Equipamentos",
    element: EquipmentPage,
    title: "Equipamentos",
    isPrivate: true,
    Permissions: [],
    icon: faToolbox,
  },
  {
    path: "/Supervisao",
    element: SupervisionPage,
    title: "Supervisao",
    isPrivate: true,
    Permissions: [],
    icon: faMagnifyingGlass,
  },
  {
    path: "/Diretoria",
    element: DirectionPage,
    title: "Diretoria",
    isPrivate: true,
    icon: faUserTie,

    Permissions: [],
  },
  {
    path: "/Settings",
    element: SettingsPage,
    title: "Configuracoes",
    isPrivate: true,
    Permissions: [],
    icon: faScrewdriverWrench,
  },
  {
    path: "/",
    element: LoginPage,
    title: "Login",
    isPrivate: false,
  },
];
